# Mailing
mail:
  protocol: smtp
  smtp:
    host: smtp.gmail.com
    port: 587
  support:
    username: amerida.transoft@gmail.com
    password: Transoft1!
# config data bases
spring:
  #profiles: test
  #main:
    #web-environment: false
  #add disable this option jmx
  #jmx:
    #enabled: false
# Datasource and JPA configuration to be used for using the same tokenstore as the authorization server for
# the defined resource server. Note that there can't be 2 different root nodes, so datasource falls under the "spring" node.
  datasource:
    url: jdbc:mysql://localhost:3306/config_general
    username: root
    password: mysql
    driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      #ddl-auto: create
      show_sql: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG

  # Logger-specific levels.
  loggers:

    # Redirects SQL logs to a separate file
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG

# modified enable option
server:
  port: 8083

#
#tomcat:
  #version: 8.0.32

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

