server:
  port: 8083
# config registry eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: product

# modified enable option
#server:
  #port: 8083

#
#tomcat:
  #version: 8.0.32

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.101.201:8761/eureka/

---

spring:
  profiles: test

# modified enable option
#server:
  #port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/