# config data bases
spring:
# config bus
  cloud:
# config rabbitmq
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.3.91 #config ip rabbitmq and for docker change the host for the ip of your machine
                port: 5672
                username: admin
                password: admin
  jackson:
    serialization:
      write-dates-as-timestamps: false
  #profiles: test
  #jmx:
    #enabled: false
# Datasource and JPA configuration to be used for using the same tokenstore as the authorization server for
# the defined resource server. Note that there can't be 2 different root nodes, so datasource falls under the "spring" node.
  datasource:
    url: jdbc:mysql://192.168.3.94:3306/payme
    username: root
    password: Transclick1!
    driver-class: com.mysql.jdbc.Driver
    initialize: true
    separator: ^
    continueOnError: false
    schema: classpath:/db-scripts/0.0.1/schema.sql
    #data: classpath:/db-scripts/0.0.1/masterData.sql
#
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      #ddl-auto: create
      show_sql: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: 
    com.transclick.land.payme: DEBUG

  # Logger-specific levels.
  loggers:

    # Redirects SQL logs to a separate file
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
# config hystrix
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=4000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
          #semaphore:
            #maxConcurrentRequests: 20
# Note: import disable mode product and active mode Dev
server:
  port: 8081
#spring:
  #application:
    #name: payme
  #config:
    #name: payme

eureka:
  client:
    serviceUrl:
      #defaultZone: http://actuator:password@localhost:8761/eureka/
      defaultZone: http://192.168.3.95:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

security:
  oauth2:
    resource:
      userInfoUri: http://192.168.3.95:9999/uaa/api/user
# config service link be
web-service:  
  link-be:
    cod-institution: '1054'
    cod-commerce: '0375140'
    cod-terminal: '02179999'
    key-registry: 'TransclickEC2020'
    service: 'ECOMME'
    key-public: 'src/main/resources/rsa/public.rsa'
    key-private: 'src/main/resources/rsa/private.rsa'
    key-link: 'src/main/resources/rsa/lksts.rsa'
    path-ps: true
debug: true
