# config data bases
spring:
# config bus
  cloud:
# config rabbitmq
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1 #config ip rabbitmq and for docker change the host for the ip of your machine
                port: 5672
                username: admin
                password: admin
  #profiles: test
  #jmx:
    #enabled: false
# Datasource and JPA configuration to be used for using the same tokenstore as the authorization server for
# the defined resource server. Note that there can't be 2 different root nodes, so datasource falls under the "spring" node.
  datasource:
    url: jdbc:mysql://localhost:3306/complet?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: mysql
    driver-class: com.mysql.jdbc.Driver
    initialize: true
    separator: ^
    continueOnError: false
    #schema: classpath:/db-scripts/0.0.1/schema.sql
    #data: classpath:/db-scripts/0.0.1/masterData.sql
#
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      #ddl-auto: create
      show_sql: true
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  cache:
    ehcache:
      config: classpath:/etc/cache/ehcache.xml
# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: 
    com.transclick.land.saleland: DEBUG

  # Logger-specific levels.
  loggers:

    # Redirects SQL logs to a separate file
    org.hibernate.SQL: DEBUG
    org.springframework: DEBUG
# config hystrix
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=4000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
          #semaphore:
            #maxConcurrentRequests: 20
#mybatis:
#  mapper-locations: classpath*:/etc/mybatis/*Mapper.xml
#  type-aliases-package: com.transclick.land.saleland.core
# Note: import disable mode product and active mode Dev
server:
  port: 8082
#spring:
  #application:
    #name: payme
  #config:
    #name: payme

eureka:
  client:
    serviceUrl:
      #defaultZone: http://actuator:password@localhost:8761/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

security:
  oauth2:
    resource:
      userInfoUri: http://127.0.0.1:9999/uaa/api/user

debug: true
